### ISSUE TITLE
Realtime widget - details text

### ISSUE THREAD

**Issue by flokuek** [sylvainjule/kirby-matomo#11]
The details text for the real-time widget seems to show the wrong label?

<img width="219" alt="capture" src="https://user-images.githubusercontent.com/11317959/53297106-ed473100-386c-11e9-8d11-497ae6db2015.PNG">
<img width="233" alt="capture2" src="https://user-images.githubusercontent.com/11317959/53297140-b9b8d680-386d-11e9-971f-f30701901fa6.PNG">

**Comment by sylvainjule** [comment]
I cannot reproduce this. Did the latest releases fixes the issue on your end?

**Comment by sylvainjule** [comment]
@flokuek closing this since I don't have the problem in several installs. Please feel free to reopen if not fixed.

**Comment by luxlogica** [comment]
@sylvainjule would it be possible to reopen this issue? This is happening on *all* sites for me - absolutely reproducible. The label is only correct when there are "0" visitors. Any number > 0 will display both options in the json array notation...

<img width="311" alt="Screen Shot 2019-09-01 at 11 13 38 am" src="https://user-images.githubusercontent.com/2994472/64070705-a702dc80-ccaa-11e9-9e3a-ac12a9c6aaa7.png">
