### ISSUE TITLE
Use Custom Routes for Pages

### ISSUE THREAD

**Issue by luxlogica** [sylvainjule/kirby-matomo#19]
We are currently deploying a site that makes extensive use of custom routes to 'remap' a page's native URL to a more logical and user-memorable one. So, for example, an article on URL...:

https://example.com/home/content/articles/movies-to-watch-with-your-dog

...becomes:

https://example.com/pets/movies-to-watch-with-your-dog

Matomo is already able to catch this, and tracks all visits to custom-routed URLs normally in the Matomo dashboard. Unfortunately, we cannot use the 'page widget' in the Panel, because it looks for the tracked data based on the 'original' (non-routed) URL...

It would be nice if we could let the plugin know that certain pages have custom URLs, so it could retrieve the data from the 'correct' URL instead. Maybe this could be done through a plugin option, or - better still - through a custom blueprint option using the query language. Something like this, in our page's _article.yml_ blueprint:

```xml
options:
  matomopath: "https://example.com/{{page.category}}/{{page.slug}}"
```

**Comment by sylvainjule** [comment]
The page widget should now detect the public URLs of pages to adjust its URI(s), see https://github.com/sylvainjule/kirby-matomo#63-potential-pitfalls. 

I have a version with a `customuri` option on the eponym branch, but it felt more tedious than this model-based detection.
