### ISSUE TITLE
Plugin use with Vue-Matomo

### ISSUE THREAD

**Issue by zhampu** [sylvainjule/kirby-matomo#24]
I'm trying to use this plug in with with [Vue matomo](https://github.com/AmazingDreams/vue-matomo) and not getting information in the tab view.
have you tried this combination to check if it works?

**Comment by sylvainjule** [comment]
I am not sure how you'd think the two could be connected / interfering? 
Seems like Vue matomo facilitates setting up tracking in your frontend. Then Matomo collects and stores the data. Then this plugin displays it. 

Does anything show up in your regular Matomo dashboard?

**Comment by sylvainjule** [comment]
Closing this, don't hesitate to reopen with additionnal informations.
