### ISSUE TITLE
Please add an option to cache matomo.js script

### ISSUE THREAD

**Issue by ankeknicker** [sylvainjule/kirby-matomo#26]
currently I'm trying to cache the downloaded matomo.js tracking script, because not caching it causes an performance issue in PageSpeed Insights.

would be cool to have an option to cache the matomo.js script with your plugin.

**Comment by sylvainjule** [comment]
Do you have a live example maybe? I think it's rather related to your server setup, because it is served from cache on all my websites.

**Comment by sylvainjule** [comment]
Closing this, don't hesitate to reopen with more details.
