### ISSUE TITLE
No data displayed!

### ISSUE THREAD

**Issue by DominiqueVial** [sylvainjule/kirby-matomo#27]
Hello !

I have installed and configured the Matomo plugin but no information is displayed and no error is displayed to understand what it's all about.

1. I've been using Matomo for a while so the data exists
2. the URL + siteId + token information are correctly filled in
3. When I click on the Matomo link of the plugin I arrive correctly at my destination!
4. the Debug option is set to true in the configuration

- Matomo v4.0.0
- working on localhost

I don't know how to solve the problem. :-(

![Capture d’écran 2020-11-25 à 19 14 53](https://user-images.githubusercontent.com/43033637/100266712-8a5b6000-2f52-11eb-87ca-c98d1c3368cc.jpg)

**Comment by guillaumeschmitz** [comment]
Hello,

I have the same issue, I think that I have configured correctly the plugin but there is no data.

kirby-matomo plugin in the plugin folder
![Capture d’écran 2020-12-03 à 10 30 37](https://user-images.githubusercontent.com/64399571/100991285-1f61e880-3553-11eb-9803-8b7650e93b23.png)

config.php
![Capture d’écran 2020-12-03 à 10 31 00](https://user-images.githubusercontent.com/64399571/100991499-589a5880-3553-11eb-9733-4f10776fb4a1.png)

snippet in my index.php
![Capture d’écran 2020-12-03 à 10 31 39](https://user-images.githubusercontent.com/64399571/100991534-64861a80-3553-11eb-9d89-c5efab896a86.png)

The result in Kirby Panel
![Capture d’écran 2020-12-03 à 10 31 49](https://user-images.githubusercontent.com/64399571/100991571-7071dc80-3553-11eb-87ff-9d267918dfb3.png)

The result in Matomo, seems to work
![Capture d’écran 2020-12-03 à 10 32 09](https://user-images.githubusercontent.com/64399571/100991602-7b2c7180-3553-11eb-93c3-a8cc15190320.png)

It seems that the snippet doesn't generate any code in the source
![Capture d’écran 2020-12-03 à 10 32 32](https://user-images.githubusercontent.com/64399571/100991642-88496080-3553-11eb-922c-28846680ffc3.png)

I hope you can help :) Thank you

**Comment by sinanatra** [comment]
exact same issue when i updated matomo to the  4.0.4

**Comment by pReya** [comment]
Same here. Plugin seems to be incompatible with recent Matomo versions.

**Comment by Brumonti** [comment]
Same here. Everything seems to be correctly set up, but no data.

**Comment by pReya** [comment]
Matomo removed the API response format `php` which the Matomo plugin was using. See https://github.com/matomo-org/matomo/issues/8100.

The plugin should probably be refactored to use the `json` format.

**Comment by pReya** [comment]
I created a PR to fix this problem in #29. Maybe @sylvainjule can take a look?
