### ISSUE TITLE
still no data

### ISSUE THREAD

**Issue by Brumonti** [sylvainjule/kirby-matomo#30]
even with the fix in V 1.0.6 no data get displayed.

In the readme it says to copy ```<?php echo snippet('matomo') ?> ```into the footer. Later it says to put this somewhere ```<?php snippet('matomo'); ?>``` but both echos don't seem to work. The snippet doesn't get inserted.

**Comment by sylvainjule** [comment]
You don't need the `echo` bit, only copy-paste `<?php snippet('matomo'); ?>` should work.

The plugin runs a [couple of checks](https://github.com/sylvainjule/kirby-matomo/blob/11d754eb15f7c37cf0877095e50b407f66715096/lib/matomo.php#L8) before inserting the snippet. Please check:

1. That you have filled an `sylvainjule.matomo.id` and `sylvainjule.matomo.url`
2. That `sylvainjule.matomo.active` hasn't been set to `false` in your config
3. Try to set `'sylvainjule.matomo.debug' => true`. If the snippet is inserted, then check:
    3. If your IP is blacklisted: the list is [here](https://github.com/sylvainjule/kirby-matomo/blob/11d754eb15f7c37cf0877095e50b407f66715096/index.php#L12)
    4. f you are logged in in the panel and the `sylvainjule.matomo.debug` is set to `true`, then it's normal than the snippet won't show.

**Comment by Brumonti** [comment]
Simple fault on my side: I had placed the array with the plugin settings  on the wrong place in my config file, so it collided with other settings there. Not an expert in this.

Sorry to have bothered you! 

Now your plugin works like charm.

**Comment by sylvainjule** [comment]
Great that you got it to work! 👍
