### ISSUE TITLE
too many request

### ISSUE THREAD

**Issue by batgithub** [sylvainjule/kirby-matomo#31]
Hi!
Since I have updated Matomo 3.6 to 4.2, only one widget (randomly) working.

For exemple here I only have the chart working :
<img width="1483" alt="Capture d’écran 2021-02-25 à 14 10 50" src="https://user-images.githubusercontent.com/4511699/109169107-c5527700-777f-11eb-95a2-3198702d9ac9.png">

This type of error showing up for 4 other calls :
`error: "file_get_contents(https://mydomain.fr/?module=API&amp;methth=mytoken&amp;format=JSON&amp;urls[0]=method%3DVisitsSummary.getVisits%26idSite%3D3%26period%3Dday%26date%3Dtoday&amp;urls[1]=method%3DVisitsSummary.getVisits%26idSite%3D3%26period%3Dday%26date%3Dlast7&amp;urls[2]=method%3DVisitsSummary.getVisits%26idSite%3D3%26period%3Dmonth%26date%3Dtoday&amp;urls[3]=method%3DVisitsSummary.getVisits%26idSite%3D3%26period%3Dyear%26date%3Dtoday): failed to open stream: HTTP request failed! HTTP/1.1 429 Too Many Requests\r\n"`

I have tested all the request individually and they are working.

Have you any clue about this error ?

Thanks

**Comment by sylvainjule** [comment]
I haven't encountered this. A 429 error indicates that you've reached the rate limit of Matomo's API. Too many requests too quickly (I've no clue what are the default Matomo API rate limitations though). Is it the only service to use the API?

**Comment by batgithub** [comment]
Thanks for your answer, I'll investigate on my Matomo installation and my hoster.
