### ISSUE TITLE
No data display but works after "cleanCache" from Janitor

### ISSUE THREAD

**Issue by psntr** [sylvainjule/kirby-matomo#34]
Hi,

I'm trying the plugin and so far it works well. Except, that after some visits, the panel starts to show "no data displayed". When I check the console, it took 2 minutes to try to fetch the API and finally it returns "failed to open stream". 

But if I use the Janitor buit-in job "cleanCache" from Janitor plugin. It works? I didn't set anything in the config.php regarding the cache. I know my host (gandi) used varnish, but not sure it is related? Any clues?

**Comment by sylvainjule** [comment]
(the plugin doesn't rely on Kirby's cache at all, I would assume the fact the you got it working after using the janitor's job was a coincidence.)

I had issues with inconsistent responses with file_get_contents. Switching to curl (with the help of the `Kirby\Http\Remote` class) fixed them for me. 
Can you give the latest release a shot with Kirby 3.6?

**Comment by psntr** [comment]
Thank you for the reply and my apologies for the late answer. I updated to Kirby 3.6 and when my connexion or when the server bandwidth is "fast" enough, the data are fetched without issue, but sometimes I got the timeout error message but as I said it must be my server settings.

I guess it's solved since the update to Kirby 3.6.
