### ISSUE TITLE
Cache folder seems to be empty when this plugin is active

### ISSUE THREAD

**Issue by psntr** [sylvainjule/kirby-matomo#38]
Hello there,

I notice this issue with the websites I'm working with. Separate hosting but same issue when this plugin is active, the cache folders doesn't create the static files cache although the folders does get created. 

When I disable the plugin and run Matomo manually it's working. 

Any ideas where that could come from?

**Comment by psntr** [comment]
Thank you for the reply and the information, I wasn't aware of that current issue. Let's hope this got solved with the next release, because your plugin is a must!

**Comment by sylvainjule** [comment]
Fixed in later versions ✓
