### ISSUE TITLE
/ at the end of the url 

### ISSUE THREAD

**Issue by idrisyangui** [sylvainjule/kirby-matomo#4]
> 3.1. url (required)
> 
> Where your matomo install is:
> 
> `'sylvainjule.matomo.url' => 'https://analytics.yourdomain.com'`

At the end of the url if I forgot the "/" the snippet matomo doesn't work with my installation of matomo. Is this the expected behavior ?

**Comment by sylvainjule** [comment]
How is it written in the tracking code generated by Matomo itself? Seems like slashes are required, yes. 🤔

**Comment by sylvainjule** [comment]
Should be fixed ✅
