### ISSUE TITLE
Compatibility with Kirby v4

### ISSUE THREAD

**Issue by andreasba** [sylvainjule/kirby-matomo#45]
Good afternoon

I tried the plugins blueprints in the panel with the most current Kirby v4 alpha but it does not work - I get some weird API redirects.

Are there plans to make the plugin work with v4?

Thanks
Andreas

**Comment by andreasba** [comment]
Thanks for the great plugin @sylvainjule - since Kirby 4 is now in beta, do you think there will be an update of the plugin anytime soon?

Also, there is a great PR which could be useful to include: https://github.com/sylvainjule/kirby-matomo/pull/43 

Thanks!

**Comment by christianschley** [comment]
I'd be very interested in an updated version for v4 as well :)

**Comment by twiro** [comment]
> I'd be very interested in an updated version for v4 as well :)

Me too 👍

**Comment by sylvainjule** [comment]
2.0.0 is now compatible with K4 ✓
