### ISSUE TITLE
this.load is not a function

### ISSUE THREAD

**Issue by thin-k-design** [sylvainjule/kirby-matomo#48]
In Kirby 3.10.0.1 I have the same issue as #37 with the error "this.load is not a function". Plugin Version 2.0.1. In the JS console the error appears twice corresponding to the components/sidebar.vue and components/main.vue files.

```
index.js:1 TypeError: this.load is not a function
    at a.created (index.js?1714844182:67:106755)
    at dn (vue.js:11:21987)
    at Be (vue.js:11:18221)
    at e._init (vue.js:11:43012)
    at new a (vue.js:11:40283)
    at vue.js:11:33227
    at init (vue.js:11:33258)
    at vue.js:11:67703
    at d (vue.js:11:67980)
    at m (vue.js:11:68556)
```

![Screenshot 2024-05-14 083710](https://github.com/sylvainjule/kirby-matomo/assets/4499116/3c82d58b-594a-4e45-b1da-94de7ac6eaab)

I don't know what is causing it, maybe a kirby issue, not a plugin issue? This is the default panel area of the matomo plugin, I haven't added any blueprints and have added only the basic configuration parameters 'sylvainjule.matomo.url', 'sylvainjule.matomo.id' and 'sylvainjule.matomo.token'. I have deleted the media/panel folder, but the error persists.

![Screenshot 2024-05-14 084034](https://github.com/sylvainjule/kirby-matomo/assets/4499116/235b83c5-8010-4e03-85c9-b70d038b4465)

**Comment by sylvainjule** [comment]
Which version of kirby-matomo are you using?

**Comment by thin-k-design** [comment]
I updated the description above, Plugin Version 2.0.1

**Comment by thin-k-design** [comment]
My bad, I interpreted 
`Kirby 3: up to 1.0.7 Kirby 4: 2.0.0+`
as the Subversions of Kirby 3 and 4.
With plugin 1.0.7 it works, I just don't get any data on my blueprint, but it's probably just a typo in the token or something like that.
