### ISSUE TITLE
Change from 'piwik' to 'matomo' may be needed in snippet

### ISSUE THREAD

**Issue by luxlogica** [sylvainjule/kirby-matomo#6]
I couldn't get the built-in snippet to work in a site I'm building atm, and when I pasted the javascript snippet directly from Matomo, it worked. When comparing the 2, the only things I could notice different were

1. the slash at the end of the Matomo URL - which the snippet didn't add (either a check should be added in the snippet, or the docs should explicitly mention it)
2. the fact that the snippet refers to 'piwik.php' and 'piwik.js', when the new versions of Matomo now use 'matomo.php' and 'matomo.js'.

To be totally honest, not sure whether the change from 'piwik' to 'matomo' was the cause, but it's my best guess...

Once again, thank you SO MUCH for such a terrific plugin.

**Comment by sylvainjule** [comment]
Yes, has been changed in the latest updates. I've updated the plugin, and added a check for trailing slash ✅
Thanks for reporting :)
