### ISSUE TITLE
Please Add a 'Buy Me a Coffee/Beer' Button 😁

### ISSUE THREAD

**Issue by luxlogica** [sylvainjule/kirby-matomo#7]
Many developers using your plugin may already have affiliate links of their own to purchase a Kirby license. You can make it easy for _anyone_ to contribute a little to your costs by adding a 'buy me a coffee' or 'buy me a beer' button in your docs, too! 😉

**Comment by sylvainjule** [comment]
Thanks for the suggestion, I've added a Paypal.me link if anyone wants to contribute 😉
