### ISSUE TITLE
Composer problem

### ISSUE THREAD

**Issue by S1SYPHOS** [sylvainjule/kirby-matomo#9]
When installing your (excellent) plugin via composer, I get this:

The section type "matomo-main" is not valid

.. when trying to include it in my blueprint .. any ideas?

**Comment by sylvainjule** [comment]
Hmm, this is weird.

As a first step have you tried clearing the bundled plugin JS to force Kirby to compile it again (`media/plugins/.index.js`)?

**Comment by S1SYPHOS** [comment]
I did, but it doesn't do anything. When adding it manually, everything works as expected, though.

**Comment by sylvainjule** [comment]
I will very soon update everything following the new Pluginkit guidelines, hopefully it will fix this issue.

**Comment by S1SYPHOS** [comment]
Well, I just checked and the Composer package seemed outdated, too -  the tracking script snippet `matomo.php` had `piwik.js` in it :confused:

**Comment by sylvainjule** [comment]
Should be fixed with the latest release?

**Comment by sylvainjule** [comment]
Closing this for more clarity in my timeline. Please feel free to reopen if the issue persists.
